---
- name: Installation du serveur Apache
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Mise à jour du cache apt
      apt:
        update_cache: true
      tags: never

    - name: Installation du serveur Apache
      package:
        name: "{{ apache_package_name }}"
        state: present

    - name: Activation et démarrage du service
      systemd:
        name: "{{ apache_service_name }}"
        state: started
        enabled: true

    - name: Modification du port d'écoute
      lineinfile:
        path: "{{ apache_port_file }}"
        regex: ^Listen 
        line: Listen {{ apache_port }}
      notify: restart_apache

    - meta: flush_handlers

    - name: Tâche bidon
      debug:
        msg: C'est presque fini !
      notify: restart_apache
      changed_when: true

  handlers:
    - name: Redémarrage du service Apache
      systemd:
        name: "{{ apache_service_name }}"
        state: restarted
      listen: restart_apache
