---
- name: Installation du serveur Apache
  hosts: servers
  become: true
  gather_facts: false

  tasks:
    - name: Mise à jour du cache apt
      apt:
        update_cache: true

    - name: Installation du serveur Apache
      package:
        name: apache2
        state: present

    - name: Activation et démarrage du service
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: Modification du port d'écoute
      lineinfile:
        path: /etc/apache2/ports.conf
        regex: ^Listen 80$
        line: Listen 81
      notify: restart_apache

    - meta: flush_handlers

    - name: Tâche bidon
      debug:
        msg: C'est presque fini !
      notify: restart_apache
      changed_when: true

  handlers:
    - name: Redémarrage du service Apache
      systemd:
        name: apache2
        state: restarted
      listen:
        - restart_apache
        - autre_canal
