---
- name: Installation du serveur Apache
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Mise à jour du cache apt
      apt:
        update_cache: true
      when: ansible_distribution|lower == 'debian'

    - name: Installation du serveur Apache
      package:
        name: "{{ apache_package_name }}"
        state: present

    - name: Activation et démarrage du service
      systemd:
        name: "{{ apache_service_name }}"
        state: started
        enabled: true

    - name: Arrêt et désactivation du service firewalld sur CentOS
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: ansible_distribution|lower == 'centos'

    - name: Modification du port d'écoute
      lineinfile:
        path: "{{ apache_port_file }}"
        regex: ^Listen 
        line: Listen {{ apache_port }}
      notify: restart_apache

    - name: Déploiement du fichier index.html
      template:
        src: html/index.html.j2
        dest: "{{ apache_html_dir }}/index.html"
        owner: "{{ apache_html_owner }}"
        mode: 0600
      tags: index

  handlers:
    - name: Redémarrage du service Apache
      systemd:
        name: "{{ apache_service_name }}"
        state: restarted
      listen: restart_apache
