---
- name: Module raw et idempotence
  hosts: srv1

  tasks:
    - name: Commande whoami
      raw: whoami
      register: result
      changed_when: result.rc != 0

    - name: Affichage de la variable result
      debug:
        msg: "result: {{ result }}"
