---
- name: Introduction aux variables
  hosts: srv1

  vars:
    stage: ansible Initiation+Approfondissement
    stagiaires:
      - André
      - Younes
      - Déborah
      - Frédéric
      - Mamadi
    formation:
      intitulé: Ansible
      début: 2022-04-25
      fin: 2022-04-29

  tasks:
    - name: Utilisation d'une variable scalaire
      debug:
        msg: "Stage: {{ stage }}"

    - name: Utilisation d'une variable de liste
      debug:
        msg: "Liste des stagiaires: {{ stagiaires }}"

    - name: Accès à un élément d'une liste
      debug:
        msg: "Premier stagiaire: {{ stagiaires[0] }}"

    - name: Utilisation d'une variable tableau associatif
      debug:
        msg: "Formation: {{ formation }}"

    - name: Accès à une clé d'un tableau associatif
      debug:
        msg: "Intitulé: {{ formation.intitulé }}"
