---
- name: Introduction aux variables
  hosts: srv1

  vars:
    stage: ansible Initiation+Approfondissement
    stagiaires:
      - André
      - Younes
      - Déborah
      - Frédéric
      - Mamadi

  tasks:
    - name: Utilisation d'une variable scalaire
      debug:
        msg: "Stage: {{ stage }}"

    - name: Utilisation d'une variable de liste
      debug:
        msg: "Liste des stagiaires: {{ stagiaires }}"
